### ISSUE TITLE
use -UseBasicParsing for Invoke-WebRequest

### ISSUE THREAD

**Issue by KonTheCat** [wetling23/Public.AEM.PowershellModule#1]
This is essential for this module to be executable from a cloud environment.

I would like to collaborate on this if possible, AEM just became a part of the job description for me so I have a very direct need for this. 

Thank you for this, what is here helped me get what I needed done right now.

**Comment by wetling23** [comment]
Good catch, I'll make that change this week and I'm totally happy to accept contributions (let's try to keep the logging style intact across the module). I've been adding to it bit-by-bit as I need new functionality.

**Comment by KonTheCat** [comment]
I would actually like to do that, already have done that on my fork of the module. On a completely unrelated note, would you mind an alteration of the behavior of New-AemApiAccessToken? I would like for it to return just the access_token portion. This way it can be easily stored in a variable and used. This confused me a bit at the start and will probably confuse others.

**Comment by wetling23** [comment]
Hey, please don't modify the contents of any files in the bin directory. Instead, update the individual functions in the Public and Private directories. Then, be sure to update the .psd1 too, so we track build versions correctly. 

I've am going back and moving the changes you made in ...\bin\1.0.0.4\AutoTaskEndpointManagement\AutoTaskEndpointManagement.psm1 to the individual cmdlet files and will build 1.0.0.5.

Incidentally, this project is also published to https://www.powershellgallery.com/packages/AutoTaskEndpointManagement.

Thanks.

**Comment by KonTheCat** [comment]
Absolutely, thank you for explaining that to me, going forward I will do things that way.

How should I point the tests to import the module?

Konstantin

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wetling23** [comment]
This ought to work:

`Import-Module $PSScriptRoot\..\bin\$(Get-ChildItem -Path $PSScriptRoot\..\bin | Select-Object -Last 1)\AutoTaskEndpointManagement\AutoTaskEndpointManagement.psd1`
