### ISSUE TITLE
Variable Input for Sites & Devices

### ISSUE THREAD

**Issue by s0nders** [wetling23/Public.AEM.PowershellModule#4]
Greetings all,

Currently having to parse all sites and devices and filter down the results. 
Is this a limitation of the API or PoSH module, or am I possibly missing something?

Current Solution -
`$Companies = Get-AemSites -AemAccessToken $AEMtoken -ApiUrl $site` 
`$devices = Get-AemDevice -AemAccessToken $AEMtoken -ApiUrl $site`
    `[array]$matchedDevices = @()`
    `[array]$matchedCompanies = @()`
        `ForEach ($customer in $CustomerID) {`
           ` $a = $customer.AccountName`
           ` $matchedCompanies += $Companies | ? {$_.autotaskCompanyName -like "*$($a)*" }`
            `$matchedDevices   += $devices   | ? {$_.SiteName -like "*$($a)*"}`       
}`

What I'd like to do - 
`Get-AemSites -AemAccessToken $AEMtoken -ApiUrl $site -SiteUid $VariableWithMultipleAccounts`

`Get-AemDevicesFromSite -AemAccessToken $AEMtoken -ApiUrl $site -SiteUid $VariableWithMultipleAccounts`

Can anyone point me in the right direction or help me out? 

Thanks!

**Comment by wetling23** [comment]
Use the -SiteUid parameter, it is already in the cmdlet. Please feel free to let me know if you have any other questions. Thanks.
